# model params
model_name : accloss
backbone: resnet50
loss    : arcloss
criterion: crossentropy
#-------------------
##input config
image_size: 112
embd_size: 512
class_num: 100
sample_num: 14686
#
##-------------------
## hyper params
weight_decay: !!float 5e-4
logits_scale: 64
logits_margin: 0.5
drop_ratio: 0.5

##-------------------
#optimizer
optimizer: SGD
momentum: 0.9
base_lr : 0.005
lr_steps: [18, 26, 29] #epoch

##--------------------
## run params
batch_size: 64
init_epoch: 0
epoch_num: 10
step_per_save: 100
# paths <SHOULD JUST CHANGE TRAIN DATA!>

train_data: "./data/images_list_new.txt"
valid_data: {"lfw":"./data/lfw_pair_.txt"}
test_data: ""
